from pathlib import Path

# absolute path to snakemake dir
snakemake_dir = Path(workflow.snakefile).parent.resolve()


# include default config values
configfile: f"{snakemake_dir.parent}/config/default_config.yaml"


METPHLAN_DB_FOLDER = Path(config["database_dir"]) / "metaphlan_databases"


include: "rules/input_functions.smk"
include: "rules/metaphlan.smk"


rule all:
    """Main entrypoint of the workflow. 
    """
    input:
        "Intermediate/metaphlan/merged_abundance_table.txt",
        # expand("Output/humann3_{type}_cpm.tsv", 
        # type=["genefamilies", "pathabundance", "pathcoverage"]
        # ),
