from pathlib import Path

# absolute path to snakemake dir
snakemake_dir = Path(workflow.snakefile).parent.resolve()


# include default config values
configfile: f"{snakemake_dir.parent}/config/default_config.yaml"


DB_DIR = Path(config["database_dir"])


include: "rules/sample_table.smk"
include: "rules/trimming.smk"
include: "rules/decontamination.smk"
include: "rules/metaphlan.smk"
include: "rules/humann.smk"


rule profile:
    input:
        "Profile/metaphlan_relab.tsv",
        #"Profile/viral_abundance.tsv",


rule qc:
    input:
        "Reports/quality_trimming/multiqc.html",
        expand(
            "QC/reads/{sample}_{fraction}.fastq.gz", fraction=FRACTIONS, sample=SAMPLES
        ),
        "Reports/decontamination_stats.csv",


rule functions:
    input:
        expand("Functions/humann_{type}_cpm.tsv", 
        type=["genefamilies", "pathabundance"]
        ),
        expand("Functions/humann_{type}.tsv", 
        type=["genefamilies", "pathabundance", "pathcoverage"]
        ),
